"""GPT-5 Integrator - Phase 4 (CORE INNOVATION)"""
import json
import re
from typing import List, Dict
from openai import OpenAI
from core.models import GeneratedModule, IntegratedProject
from core.config import config

class Integrator:
    def __init__(self):
        self.client = OpenAI(api_key=config.OPENAI_API_KEY)
        self.model = config.GPT5_MODEL
    
    def integrate_project(self, project_name: str, modules: List[GeneratedModule], 
                         blueprint: dict, deployment_config: dict) -> IntegratedProject:
        print(f"🔗 Integrating {len(modules)} modules...")
        
        # Generate integration files
        integration_files = self._generate_integration_files(project_name, modules, blueprint)
        requirements = self._generate_requirements(modules)
        readme = self._generate_readme(project_name, blueprint)
        docker_files = self._generate_deployment_files(project_name, deployment_config)
        
        integrated = IntegratedProject(
            project_name=project_name,
            modules=modules,
            integration_files=integration_files,
            requirements_txt=requirements,
            readme=readme,
            docker_files=docker_files,
            success=True,
            execution_report={"total_modules": len(modules)}
        )
        
        print(f"✅ Project integrated!")
        return integrated
    
    def _generate_integration_files(self, project_name: str, modules: List[GeneratedModule], blueprint: dict) -> Dict[str, str]:
        prompt = f"""Generate integration layer files.
Project: {project_name}
Modules: {[m.module_id for m in modules]}
Integration Plan: {json.dumps(blueprint.get('integration_plan', {}), indent=2)}

Generate: core/__init__.py, core/config.py, core/exceptions.py
Output JSON: {{"files": {{"path": "content"}}}}
"""
        
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=config.TEMPERATURE_INTEGRATOR,
                response_format={"type": "json_object"}
            )
            data = json.loads(response.choices[0].message.content)
            return data.get("files", {})
        except:
            return {"core/__init__.py": "# Integration layer\n"}
    
    def _generate_requirements(self, modules: List[GeneratedModule]) -> str:
        packages = set()
        for module in modules:
            for code in module.files.values():
                for line in code.split('\n'):
                    if line.strip().startswith('import ') or line.strip().startswith('from '):
                        match = re.match(r'(?:from|import)\s+([a-zA-Z0-9_]+)', line)
                        if match:
                            pkg = match.group(1)
                            if pkg not in ['os', 'sys', 'json', 'typing', 'datetime']:
                                packages.add(pkg)
        
        versions = {
            'fastapi': '0.104.1', 'uvicorn': '0.24.0', 'pydantic': '2.5.0',
            'sqlalchemy': '2.0.23', 'anthropic': '0.72.0', 'openai': '2.6.1',
            'python-dotenv': '1.2.1'
        }
        
        lines = []
        for pkg in sorted(packages):
            if pkg in versions:
                lines.append(f"{pkg}=={versions[pkg]}")
            else:
                lines.append(pkg)
        return '\n'.join(lines)
    
    def _generate_readme(self, project_name: str, blueprint: dict) -> str:
        modules = blueprint.get('execution_order', [])
        return f"""# {project_name}

## Modules
{chr(10).join([f"- {m}" for m in modules])}

## Setup
```bash
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
cp .env.example .env
# Edit .env
python main.py
```

Generated by Archon 3.0
"""
    
    def _generate_deployment_files(self, project_name: str, deployment_config: dict) -> Dict[str, str]:
        return {
            'Dockerfile': """FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "main.py"]
""",
            'docker-compose.yml': """version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
""",
            '.env.example': """OPENAI_API_KEY=your_key
ANTHROPIC_API_KEY=your_key
"""
        }
